name: Sync LeetCode Solutions

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          destination-folder: ''
          verbose: true
